reportTypo script
Hexlet/hexlet-correction pull request #110
Opened 2022-09-19 15:09 UTC by antonkrupin

create reportTypo.js
add Modal markup in index.html

2022-09-20 14:49 UTC, acidmaksim commented
@kacetal посмотришь?

2022-09-21 08:02 UTC, kacetal requested changes

2022-09-21 08:02 UTC, kacetal commented on src/main/resources/templates/index.html
> +<!-- Modal -->
то есть в модальное окно мы поместим iframe и откроем в нем обычную страницу, но сама страница не будет модалкой это будет форма обычная

2022-09-21 08:06 UTC, kacetal requested changes

2022-09-21 08:06 UTC, kacetal commented on src/main/resources/static/js/reportTypo.js
> +      Authorization: 'Token e3844052-4bb9-4e54-99b7-b8705365d521',
токен мы не будем показывать, будем использовать iframe и [CSP: frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)

2022-09-26 09:24 UTC, ashikov commented
@antonkrupin как тут дела? Может быть есть какие-то вопросы?

2022-09-26 09:55 UTC, antonkrupin commented
@ashikov добрый день, пока ничего не делал, сегодня вечером попробую заняться. Если вопросы появятся, я здесь напишу. P.S. после 21 числа немного не до этого было.

2022-09-29 05:09 UTC, ashikov commented
@antonkrupin что-то получилось? Понимаю, что сейчас сложно собраться с мыслями, но задачка подвисла, хорошо бы её добить.

2022-09-29 05:27 UTC, antonkrupin commented
@ashikov добрый день, вроде бы что получается, сегодня постараюсь закончить.

2022-09-30 12:01 UTC, antonkrupin commented
Добрый день, в iframe модальное окно перенес. не могу понять как мне передавать данные на сервер, если мы токен не показываем и не используем. выше писали что нужно использовать - iframe и CSP: frame-ancestors, но я не знаю как это использовать.

2022-10-10 08:43 UTC, kacetal requested changes

2022-10-10 08:43 UTC, kacetal commented on src/main/resources/templates/index.html
> +<!-- Modal -->
Смотри, ты не должен трогать "index.html". Создай форму в отдельном файле, например "typo-form.html"

2022-10-10 08:56 UTC, antonkrupin commented on src/main/resources/templates/index.html
> +<!-- Modal -->
Это я сделал - вынес форму в отдельный htlm и теперь ее можно подключить через <iframe> (ПР пока не делал).

2022-10-17 11:06 UTC, dzencot commented
Тут ещё ведётся работа?

2022-10-17 11:09 UTC, acidmaksim commented
> Тут ещё ведётся работа?

Да, но студент застрял и не понимает как реализовать

2022-10-19 16:24 UTC, antonkrupin commented
![image](https://user-images.githubusercontent.com/18227707/196748993-08033608-3351-4fa3-9b9d-2a9e784760c6.png)
сделал ПР с отделенным модальным окном, его добавляю через iframe. появляется вот такая ошибка.

2022-10-24 11:34 UTC, acidmaksim commented
@ashikov к тебе или к кому по этой задачке лучше обратиться ?

2022-10-25 12:50 UTC, acidmaksim commented
@dzencot возможно здесь понадобится твоя помощь, пока Ромы нет. Это фронтовая задача вроде

2022-11-14 09:02 UTC, kacetal commented
Я добавил необходимую функциональность на beckend, мы будем отдавать этот widget "widget/typo-form".

2022-11-14 09:02 UTC, kacetal commented
Его можно будет встроить через iframe "<iframe src="http://localhost:8080/typo/form/{workspace-name}"></iframe>"

2022-11-14 09:05 UTC, kacetal commented
скрипт должен заполнить все скрытые поля у отданой формы. При окончании загрузки форма будет отсылать сообщение родителю что загрузка завершена.

2022-11-14 09:07 UTC, kacetal commented
Думаю лучше всего отдавать не только форму, а готовую модалку и желательно сверстать это без бутстрапа на чистом css html чтобы не тянуть лишние зависимости для одной модальки.

2022-11-14 09:08 UTC, kacetal commented
Если будут вопросы пиши сюда. И перед началом работы поднимись на последний коммит в main

2022-11-21 14:13 UTC, antonkrupin commented
Освобождаю задачу, времени не хватает

2022-11-25 13:05 UTC, closed without merging