[96] add login signin page
Hexlet/hexlet-correction pull request #112
Opened 2022-09-22 14:47 UTC by Kvas1988

Реализовал базовую аутентификацию, и регистрацию.
Добавил темплейты для регистрации пользователя и логина.
![image](https://user-images.githubusercontent.com/25788591/191778740-5c339de1-a95c-4fb2-8b93-1d6ff2db1ad3.png)

Из-за появления авторизации, тесты, связанные с контроллерами требуют переработки. 
После принятия пулреквеста создадим под это отдельный ишью

2022-09-23 09:32 UTC, ashikov commented
Здесь бы конфликты разрулить
#96

2022-09-26 16:07 UTC, Kvas1988 commented
Сделал фикс для теста AccountRepositoryIT.getPageAccountByWorkspaceName.
Пароли для аккаунтов в тестовых датасетах были меньше 8-ми символов.

2022-09-28 08:23 UTC, kacetal requested changes

2022-09-28 18:30 UTC, Kvas1988 commented on pom.xml
> +            <artifactId>thymeleaf-extras-springsecurity4</artifactId>
[thymeleaf security dialect 5](https://github.com/Hexlet/hexlet-correction/pull/112/commits/199a22dc0afa46e6b5f01321b4fb8a4cf2851f2d)

2022-09-28 18:30 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/security/service/AccountPasswordEncoder.java
> +    @Bean("bCryptPasswordEncoder")
Got a cycle dependencies when put bCryptoPasswordEncoder bean in SecurityConfig
```
┌─────┐
     securityConfig
↑     ↓
     accountAuthenticationProvider
└─────┘
```

2022-09-28 18:45 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        sourceAccount.setExternalOpenId("1L");
https://github.com/Hexlet/hexlet-correction/blob/6cb195d9acf4a214419addfba8d1cf24eeac6ee3/src/main/java/io/hexlet/typoreporter/domain/account/Account.java#L41-L45

This is field has NotNull annotation. 
Also this field has not null constraint in db:

https://github.com/Hexlet/hexlet-correction/blob/6cb195d9acf4a214419addfba8d1cf24eeac6ee3/src/main/resources/db/changelog/changesets/2022/04/20220428163604-create-account-table.xml#L41-L42

2022-09-28 18:47 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/config/SecurityConfig.java
> +            .antMatchers(GET, "/debug").authenticated()
[remove debug stuff](https://github.com/Hexlet/hexlet-correction/pull/112/commits/36b5ff577d08dead64a018756f458bc3dedcdcdd)

2022-09-28 18:47 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/security/provider/AccountAuthenticationProvider.java
> +public class AccountAuthenticationProvider implements AuthenticationProvider {
[AccountAuthProvider](https://github.com/Hexlet/hexlet-correction/pull/112/commits/cc00e14ff5684f1efc189bf2d5aad88d1e1f7f07)

2022-10-02 15:08 UTC, acidmaksim commented
@kacetal тут получается еще нужны правки?

2022-10-10 08:57 UTC, kacetal requested changes

2022-10-10 08:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        sourceAccount.setExternalOpenId("1L");
Да но это для провайдера, я же говорил о "externalOpenId", он не нужен

2022-10-10 08:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/security/provider/AccountAuthenticationProvider.java
> +          throw new BadCredentialsException("Failed to authenticate. Password is wrong.");
Лучше сказать что неправильные login и пароль, не стоит говорить что именно пароль неправильный.

2022-10-10 08:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/security/service/AccountPasswordEncoder.java
> +    @Bean("bCryptPasswordEncoder")
назови его passwordEncoder и сделай @Primary если не получится используй setter а не конструктор

2022-10-10 08:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/security/service/AccountPasswordEncoder.java
> +    @Bean("bCryptPasswordEncoder")
вобщем надо так бины реорганизовать чтобы не было циклической зависимости

2022-10-11 11:33 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/security/provider/AccountAuthenticationProvider.java
> +          throw new BadCredentialsException("Failed to authenticate. Password is wrong.");
[Wrong login/password message](https://github.com/Hexlet/hexlet-correction/pull/112/commits/29b2144fc7dd04fd2e5e9a5ea99e45b88d35332e)

2022-10-11 11:36 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        sourceAccount.setExternalOpenId("1L");
[Remove NotBlank annotation for externalOpenId field](https://github.com/Hexlet/hexlet-correction/pull/112/commits/73d19ca728b1d3b1d8a25c7d81347d82bcffb196)

2022-10-11 11:37 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/security/service/AccountPasswordEncoder.java
> +    @Bean("bCryptPasswordEncoder")
Used Lazy annotation to resolve conflict
[Remove Circular Dependencies](https://github.com/Hexlet/hexlet-correction/pull/112/commits/eaa353364c71b6bf039cb1ce8ac9de83cb21a8aa)

2022-10-13 14:11 UTC, acidmaksim commented
@kacetal привет) Поревьюишь, пожалуйста?

2022-10-14 07:33 UTC, kacetal requested changes

2022-10-14 07:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    private final CreateAccountToAccount converter;
Конверетер создается через ConversionService, смотри как сделано в TypoService

2022-10-14 07:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    private final BCryptPasswordEncoder encoder;
не указывай конкретный тип

2022-10-14 07:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    private final BCryptPasswordEncoder encoder;
BCryptPasswordEncoder можешь сделать @Primary при декларации, тогда не нужно его будет постоянно указывать через @Qualifier

2022-10-14 07:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    public boolean saveAccount(Account account) {
нужно также проверять уникальность емайла, и желательно это все делать в открытой транзакции

2022-10-14 07:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        Account accountFromDB = accountRepository.findAccountByUsername(account.getUsername())
use Optional here

2022-10-14 07:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/LoginController.java
> +    public String getLoginPage(final Model model) {
не уверен что тебе нужен контроллер login , можно использовать стандартную имплементацию Spring Security

2022-10-14 07:34 UTC, kacetal commented
@Kvas1988 Это не последние замечания, исправь эти и я ещё добавлю. Но в целом довольно неплохо 👍

2022-10-17 12:07 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    public boolean saveAccount(Account account) {
[check email](https://github.com/Hexlet/hexlet-correction/pull/112/commits/be1865eb2967e2f4c80572063c57011b0b70937d)
Чет нагородил здесь :)
Вывел проверки юзернейма и почты в контроллер, чтобы выдавать соответствующие ошибки пользователю.

2022-10-17 12:09 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    private final CreateAccountToAccount converter;
[ConversionService](https://github.com/Hexlet/hexlet-correction/pull/112/commits/aa7a88f7c4c795977f7dead5b6c2313826a9cd18)

2022-10-17 12:30 UTC, Kvas1988 commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        Account accountFromDB = accountRepository.findAccountByUsername(account.getUsername())
Changed with other function returning bool (commit with unique email checking)
https://github.com/Hexlet/hexlet-correction/blob/be1865eb2967e2f4c80572063c57011b0b70937d/src/main/java/io/hexlet/typoreporter/service/AccountService.java#L23-L29

2022-10-25 14:10 UTC, merged