Add landing parge
Hexlet/hexlet-correction pull request #113
Opened 2022-09-26 06:37 UTC by niyak93rus

#111: make landing page

2022-09-29 05:02 UTC, ashikov commented
@kacetal привет! Глянь, плиз

2022-10-10 08:36 UTC, kacetal requested changes

2022-10-10 08:36 UTC, kacetal commented on src/main/resources/static/landing.html
> +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
надо использовать WebJar как это сделано в других файлах

2022-10-10 08:36 UTC, kacetal commented on src/main/resources/static/landing.html
> +  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
webJar

2022-10-12 15:14 UTC, ashikov commented
@niyak93rus тут бы поправить пару моментов о которых написал @kacetal

2022-10-14 05:14 UTC, niyak93rus commented
@ashikov @kacetal Доброго дня, внес изменения, посмотрите, как будет время пож-та

2022-10-14 07:44 UTC, kacetal requested changes

2022-10-14 07:44 UTC, kacetal commented on pom.xml
> +        <dependency>
Bootstrap уже есть на линии 69, добавлять его еще раз не надо, может просто версии обновить на более свежую и проверить что ничего не сломалось

2022-10-14 07:44 UTC, kacetal commented on pom.xml
> +        <plugins>
убери пробел

2022-10-14 07:44 UTC, kacetal commented on src/main/resources/static/landing.html
> +<head>
используй уже готовый блок head как [тут](https://github.com/Hexlet/hexlet-correction/blob/6cb195d9acf4a214419addfba8d1cf24eeac6ee3/src/main/resources/templates/index.html#L3)

если надо что добавить измены этот [файл](https://github.com/Hexlet/hexlet-correction/blob/main/src/main/resources/templates/fragments/header.html)

2022-10-14 07:44 UTC, kacetal commented on src/main/resources/static/landing.html
> +  <script src="/webjars/bootstrap/js/bootstrap.min.js"></script>
in the head

2022-10-14 09:59 UTC, niyak93rus commented on src/main/resources/static/landing.html
> +<head>
если я правильно понял, то из папки static нет доступа к шаблонам thymeleaf. то есть тег <head> у меня так просто пустой становится в итоге

2022-10-17 04:26 UTC, niyak93rus commented on src/main/resources/static/landing.html
> +<head>
@kacetal с этим не получилось, не понимаю, как правильно сделать. если я правильно понял, то из папки static нет доступа к шаблонам thymeleaf. Если я так же копирую, тег у меня пустой становится.

2022-10-28 13:56 UTC, kacetal commented on src/main/resources/static/landing.html
> +<head>
Клади в шаблоны

2022-10-31 07:11 UTC, ssssank commented
@niyak93rus доделаете? :)

2022-10-31 07:28 UTC, niyak93rus commented
@ssssank да, конечно, в ближайшие дни займусь 👍

2022-11-14 09:10 UTC, kacetal commented
перенеси картинки в static

2022-11-18 04:30 UTC, ashikov commented
@niyak93rus тыц. Вроде по мелочи осталось доделать

2022-11-23 20:19 UTC, kacetal commented
@niyak93rus Спасибо за помощь, я добавил  изменений связанных со статическими ресурсами и  контроллер для этой страницы. В остальном всё хорошо, можно мержить.

2022-11-23 20:20 UTC, merged