[#108] add account page
Hexlet/hexlet-correction pull request #115
Opened 2022-10-28 12:13 UTC by nikisysoev

Added InfoAccount dto for account info and something else
Added UpdatePassword dto for updating account password
Added UpdateProfile dto for for account information except password

Added acc-info.html for InfoAccount 
Added pass-update.html for UpdatePassword
Added prof-update.html for UpdateProfile
Added link to panels.html for acc-info.html

Added AccountToInfoAccount converter 
Added AccountToUpdateProfile converter

Added some Routers and Templates

Added EmailAlreadyExistExeption
Added PasswordNotMatchException for password confirmation while updating
Added UsernameAlreadyExistException
Added OldPasswordWrongException

Added path to SecurityConfig  for authenticated access for account updates

Added AccountController and some stuff in AccountService for account info and updating

2022-11-02 10:01 UTC, acidmaksim commented
@kacetal посмотри, пожалуйста

2022-11-05 11:13 UTC, kacetal requested changes

2022-11-05 11:13 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
Лучше это вынести на уровень контроллера и прокинуть name как аргумент

2022-11-05 11:13 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
Ты можешь заинжектить authentication напрямую в контроллер, нет необходимости обращаться к SecurityContextHolder

2022-11-05 11:13 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +    public String putProfileUpdate(final Model model,
все структурные валидации такие как проверка длины, совпадения полей и другие луче делать в контроллере, все валидации бизнес логики такие как проверка на совпадение имени лучше делать в Service и оттуда выкидывать исключение и ловить его. Посмотри на мой последний коммит в main где я добавил урл к Workspace .

2022-11-05 11:13 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +        final String password = SecurityContextHolder.getContext()
Ты можешь заинжектить authentication напрямую в контроллер, нет необходимости обращаться к SecurityContextHolder

2022-11-05 11:13 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/exception/EmailAlreadyExistException.java
> +public class EmailAlreadyExistException extends AbstractThrowableProblem {
Я сделал рефакторинг, посмотри  коммите https://github.com/Hexlet/hexlet-correction/commit/10826816459001f65138139f49ea8043da16bc95#diff-cd23190526b4c7fc77722ee6356f75293fd94d180dd8e1b2c330b52d055dc7d6R11-R27

2022-11-06 13:30 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/dto/account/UpdatePassword.java
> +    private String newPassword;
[PR feedback: add cross-field validation](https://github.com/Hexlet/hexlet-correction/pull/115/commits/7c30dd3cd9aa11f45a0a4b8bd888c9887f57755b)

2022-11-06 13:31 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
[PR feedback: inject authentication](https://github.com/Hexlet/hexlet-correction/pull/115/commits/385edc480a0f762f3a5061ce7ef80637ce4724f1)

2022-11-06 13:31 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
[PR feedback: inject authentication](https://github.com/Hexlet/hexlet-correction/pull/115/commits/385edc480a0f762f3a5061ce7ef80637ce4724f1)

2022-11-06 13:31 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
[PR feedback: inject authentication](https://github.com/Hexlet/hexlet-correction/pull/115/commits/385edc480a0f762f3a5061ce7ef80637ce4724f1)

2022-11-06 13:31 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +    public String putProfileUpdate(final Model model,
[PR feedback: add AccountAlreadyExistException](https://github.com/Hexlet/hexlet-correction/pull/115/commits/d5abc539e8853349c157266398b0a1bb520d771e)

2022-11-06 13:32 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +        final String password = SecurityContextHolder.getContext()
[PR feedback: inject authentication](https://github.com/Hexlet/hexlet-correction/pull/115/commits/385edc480a0f762f3a5061ce7ef80637ce4724f1)

[fix authentication injection](https://github.com/Hexlet/hexlet-correction/pull/115/commits/aee21c84342b7a55b3a932f4c524b14854b12520)

2022-11-06 13:33 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
[fix authentication injection](https://github.com/Hexlet/hexlet-correction/pull/115/commits/aee21c84342b7a55b3a932f4c524b14854b12520)

2022-11-06 13:33 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
[fix authentication injection](https://github.com/Hexlet/hexlet-correction/pull/115/commits/aee21c84342b7a55b3a932f4c524b14854b12520)

2022-11-06 13:33 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        final String name = authentication.getName();
[fix authentication injection](https://github.com/Hexlet/hexlet-correction/pull/115/commits/aee21c84342b7a55b3a932f4c524b14854b12520)

2022-11-06 13:33 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/dto/account/UpdatePassword.java
> +    private String newPassword;
[fix authentication injection](https://github.com/Hexlet/hexlet-correction/pull/115/commits/aee21c84342b7a55b3a932f4c524b14854b12520)

2022-11-06 13:34 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/web/exception/EmailAlreadyExistException.java
> +public class EmailAlreadyExistException extends AbstractThrowableProblem {
[PR feedback: add AccountAlreadyExistException](https://github.com/Hexlet/hexlet-correction/pull/115/commits/d5abc539e8853349c157266398b0a1bb520d771e)

2022-11-06 13:37 UTC, nikisysoev commented
@kacetal Привет! Исправил

2022-11-16 15:02 UTC, acidmaksim commented
@kacetal посмотри, пожалуйста

2022-11-16 15:39 UTC, kacetal requested changes

2022-11-16 15:39 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    @Transactional
у тебя уже стоит такая аннотация над классом, её стоит ставить только тогда когда ты переопределяешь параметры как в случае с readOnly

2022-11-16 15:39 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        if (!passwordEncoder.matches(updatePassword.getOldPassword(), password)) {
Надо ещё проверить что новый пароль не равен старому.

2022-11-18 08:48 UTC, kacetal commented
@nikisysoev смотри я добавил коммит как делать валидацию полей, исправь маппинг и фронт для него.

2022-11-21 08:36 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        if (!passwordEncoder.matches(updatePassword.getOldPassword(), password)) {
[fix transactional annotation](https://github.com/Hexlet/hexlet-correction/pull/115/commits/e874b393554dc4ac07b4826ed09907ffc2253b19)

2022-11-21 08:36 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +    @Transactional
[fix transactional annotation](https://github.com/Hexlet/hexlet-correction/pull/115/commits/e874b393554dc4ac07b4826ed09907ffc2253b19)

2022-11-21 08:37 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        if (!passwordEncoder.matches(updatePassword.getOldPassword(), password)) {
[add front and mapping cross-field validation](https://github.com/Hexlet/hexlet-correction/pull/115/commits/751a2f12a9263c5d713bd93d8bb9372115812c87)

2022-11-21 08:49 UTC, nikisysoev commented
> @nikisysoev смотри я добавил коммит как делать валидацию полей, исправь маппинг и фронт для него.

Не выводилось значения полей email при ошибке валидации, изменил сообщение при ошибке.

2022-11-21 11:25 UTC, kacetal requested changes

2022-11-21 11:25 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +            .map(oldAcc -> oldAcc.setFirstName(updateProfile.getFirstName()))
Вот это не очень хорошая конструкция, лучше сделать отдельный mapper для этих объектов.

2022-11-24 13:37 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +            .map(oldAcc -> oldAcc.setFirstName(updateProfile.getFirstName()))
[add UpdateProfileToAccount converter](https://github.com/Hexlet/hexlet-correction/pull/115/commits/8ace3e0cfb99620d49134486d400d33b0c4bdabf)

[fix Account converter](https://github.com/Hexlet/hexlet-correction/pull/115/commits/7dfcd27f195ce0c4b96dbcf403bce2b2f192bc36)

2022-11-24 21:42 UTC, kacetal approved these changes

2022-11-24 21:42 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        if (sourceAccount.isPresent()) {
В следующий раз переворачивай условия, чтобы  вся логика не была вложена внутрь одного 'if'

2022-11-24 21:42 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        if (sourceAccount.isPresent()) {
В следующий раз переворачивай условия, чтобы  вся логика не была вложена внутрь одного 'if'

2022-11-24 21:43 UTC, kacetal commented
@nikisysoev Спасибо, неплохо сделано

2022-11-24 21:44 UTC, merged

2022-11-25 06:28 UTC, nikisysoev commented
@kacetal  @acidmaksim Спасибо

2022-11-25 06:39 UTC, nikisysoev commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +        if (sourceAccount.isPresent()) {
```
 if (sourceAccount.isEmpty()) { 
      throw new AccountNotFoundException(name);
}
```
Через выкидывание исключения?