104 add roles with rights
Hexlet/hexlet-correction pull request #116
Opened 2022-11-06 01:55 UTC by 12oprs

@kacetal привет, посмотри пожалуйста. 

Максим мне еще скинул вот такой вариант:
Создатель/Creator - может создавать воркспейс, редактировать, давать права
Редактор/Editor - может редактировать и видит ключ для вставки виджета
Наблюдатель/Watcher -  может только просматривать оишбки

Но я пока сделал как написано в описании задачи. Т.к. надо еще определиться как раздавать права.

2022-11-07 08:45 UTC, emp7yhead commented
Пофиксите ошибки, тут проверки не проходят

2022-11-14 10:52 UTC, kacetal requested changes
@12oprs Вот смотри, у нас есть две сущности Workspace и Account. Каждый воркспайс может иметь много пользователей и каждый аккунт может быть присоединен к многим воркспайсам. Значит между ними будет связь ManyToMany и нужно будет создать промежуточную таблицу. И кроме ключей на сущности эта таблица будет содержать дополнительные поля которые будут ролами пользователя в определенном воркспайсе.
Сосдай пока такую таблицу, при создании пользователь не будет иметь никаких ролей, но внутри каждого воркспайса можно будет вибрать пользователя и роль для него.
Для таблицы лучше не используй композитный ключ, а сделай нормальный id и два внешних ключа.

Далее следует понимать разницу между Role и Authority. В последних версиях spring-security она минимальна. Например роль можно писать без префикса. Но семантически разница есть. Обычно роль отвечает на вопрос (to be) она говорит кем является пользователь, а Authority на вопрос (to do) то есть что он может делать. Также роль может быть контейнером для Authority в сложных иерархиях.

2022-11-18 04:21 UTC, ashikov commented
@12oprs

2022-11-22 13:51 UTC, 12oprs commented
Привет всем, недели на полторы я исчезаю, может кто-нибудь еще захочет доделать.

2022-12-15 09:57 UTC, closed without merging