added layout form
Hexlet/hexlet-correction pull request #118
Opened 2022-11-26 23:52 UTC by MilaNick

Сверстала popup и частично форму. Не совсем понимаю в правильном ли направлении я иду. Что делать дальше?

2022-11-29 15:22 UTC, kacetal requested changes
Всё верно, но лучше начать с другой стороны.

По сути у нас есть две независимые задачи:
Первая это создать скрипт который пользователь будет подключать к себе на страницу. Скрипт будет раздеваться hexlet-correction сайтом. При загрузке скрипт будет создавать listener для нажатия комбинации клавиш.
При нажатии на нужную комбинацию скрипт будет делать две вещи.
Брать выделенный текст и текст до или после выделения.
И второе он будет создавать модальное окно с iframe внутри. С такой структурой.
div это модальное окно
iframe это будет загружаемый контент.

Дальше он должен будет дождаться сообщения о загрузке от iframe и вставить значения в скрытые поля.

Начало такое. Как сделаешь эту часть можно делать следующую. И верстать контент модалки.

2022-11-29 20:54 UTC, MilaNick commented
Наверное я непонятно написала.
- _По сути у нас есть две независимые задачи:
Первая это создать скрипт который пользователь будет подключать к себе на страницу. Скрипт будет раздеваться hexlet-correction сайтом. При загрузке скрипт будет создавать listener для нажатия комбинации клавиш.
При нажатии на нужную комбинацию скрипт будет делать две вещи.
Брать выделенный текст_ 
- [x] все выше сделала
- _и текст до или после выделения._
- [ ] !  не совсем, вставляется текст из focusNode. Здесь мне нужна помощь. Не получается(((
- _И второе он будет создавать модальное окно_
- [x] сделала
 - _с iframe внутри. С такой структурой. ... iframe это будет загружаемый контент.
Дальше он должен будет дождаться сообщения о загрузке от iframe и _ 
- [ ] нет. Читаю, разбираюсь
- _вставить значения в скрытые поля._
- [x] сделала
-  _И верстать контент модалки._
- [x] сделала

2022-11-30 20:18 UTC, MilaNick commented
Привет. 
Реализовала перечисленное)
Вопросы:
1. должна ли я запустить проект? Появляется ошибка при билде.  Я разрабатывала, непосредственно запуская html-файлы. 
2. Т.к. я не подняла бекенд. у меня не происходит отправка формы на сервер и соответственно не показывается отчет об отправке и, как следствие, я не знаю, что делать с report-typo-файлами.

2022-12-03 10:47 UTC, kacetal commented
Я сегодня код проверю и расскажу как запускать

2022-12-12 09:12 UTC, kacetal requested changes
Исправь структурные проблемы, потом как исправишь это, будем исправлять выделение текста и отправку с сервера.

2022-12-12 09:12 UTC, kacetal commented on src/main/resources/templates/widget/typo-form.html
> +<head th:replace="fragments/header :: head">
если тебе не нужен бутстрап убери th:replace

2022-12-12 09:12 UTC, kacetal commented on src/main/resources/templates/widget/typo-form.html
> +    <link rel="stylesheet" href="index.css">
желательно положить этот css в static. Создай там директорию с понятным названием. И загружай через thymleaf, посмотри как это сделано с картинками для ландинга (index.html)

2022-12-12 11:21 UTC, MilaNick commented on src/main/resources/templates/widget/index.js
> +    if (e.keyCode === 13 && e.ctrlKey) {
@kacetal 
Спасибо, Артем. 
Я правильно поняла, что условие должно быть одно и выглядеть приблизительно так if (e.keyCode === 13 && e.ctrlKey & state.text.length)

2022-12-12 15:28 UTC, kacetal commented on src/main/resources/templates/widget/index.js
> +    if (e.keyCode === 13 && e.ctrlKey) {
Да можешь и два, просто их надо инвертировать и после каждого неудачного условия делать return, чтобы не создавать вложенную цепочку if.

Вдобавок условие "state.text.length" не очень хороший способ проверки. В Selection Api есть специальный метод [isCollapsed](https://developer.mozilla.org/en-US/docs/Web/API/Selection/isCollapsed).

2022-12-14 12:59 UTC, MilaNick commented on src/main/resources/templates/widget/typo-form.html
> +    <link rel="stylesheet" href="index.css">
Артем, привет. Чуть отвлекусь, делаю тестовое задание. Вернусь через пару дней.

2022-12-14 12:59 UTC, MilaNick commented
Артем, привет. Чуть отвлекусь, делаю тестовое задание. Вернусь через пару дней.

2023-01-09 10:26 UTC, dzencot commented
Тут работа еще ведется? Нужна помощь?

2023-01-10 14:44 UTC, MilaNick commented
Привет. Работа сейчас не ведется. Пытаюсь устроиться на работу, делаю тестовые. Забирает все время. Задача не закончена, если есть желание заберите.

2023-01-27 23:23 UTC, MilaNick commented on src/main/resources/templates/widget/index.js
> +    if (e.keyCode === 13 && e.ctrlKey) {
исправила

2023-01-27 23:25 UTC, MilaNick commented on src/main/resources/templates/widget/index.js
> +      if (state.text.length) {
исправила

2023-02-20 10:44 UTC, dzencot commented
Предлагаю пока в черновик убрать. Либо можем дать кому-то на доработку. @ssssank можем это дать ребятам в опенсорс?

2023-02-23 11:39 UTC, kacetal commented
@dzencot это одно из требований для mvp, его надо сделать.

2023-02-28 08:22 UTC, ashikov commented
Так убираем в draft пока или пусть висит?

2023-02-28 15:16 UTC, fey commented
Давайте сделаем Draft. И поищем того, кто продолжит работу, возможно Мила вернется к ПРу.

2023-02-28 15:18 UTC, fey commented
@kacetal подскажи, а сейчас же виджетом не пользуются?
Я предлагаю план - мы мержим что есть, если оно не мешает, заводим ишшус и в нем пишем, что нужно исправить.

2023-05-02 10:07 UTC, closed without merging