Add workspace role
Hexlet/hexlet-correction pull request #120
Opened 2022-12-07 07:41 UTC by nekedio

Changed the relationship between the account and the workspace on ManyToMany using.
Added functionality for adding an account.

2022-12-15 09:57 UTC, kacetal requested changes
Пока исправь сущности потом дальше будем двигаться.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRoleId.java
> +        return (this == o || workspaceId != null && o instanceof WorkspaceRole other && workspaceId.equals(other.id))
Длинный однострочник читать тяжелее, лучше его заменить на что то вроде этого:
```java
    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj instanceof WorkspaceRoleId other) {
            return workspaceId.equals(other.workspaceId) && accountId.equals(other.accountId);
        }
        return false;
    }
```

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRoleId.java
> +        return getClass().hashCode();
тут можешь считать hash через оба id, так как это не hibernate присваивает id а мы в коде.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRoleId.java
> +@Embeddable
add toString()

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    @ManyToOne
FetchType.LAZY

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    @ManyToOne
FetchType.LAZY

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRoleId.java
> +    @Column(name = "workspace_id")
Это можно удалить так как это стандартный маппинг имени

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRoleId.java
> +    @Column(name = "account_id")
Это можно удалить так как это стандартный маппинг имени

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    @JoinColumn(name = "account_id")
Это часть не нужна.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    @JsonIgnore
Это часть не нужна. Мы не будем сереализовывать Entity напрямую.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    @JoinColumn(name = "workspace_id")
Это часть не нужна.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +public class WorkspaceRole {
Добавь сюда и в миграцию String role длинной например 50 символов, чтобы потом еще раз не изменять сунность.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    private Account account;
Исключи эту ссылку из toString

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +    private Workspace workspace;
Исключи эту ссылку из toString

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
> +        return getClass().hashCode();
можешь тут считать hash от id, проблем не будет.

2022-12-15 09:57 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/Workspace.java
> +    public Workspace addWorkspaceRole(final WorkspaceRole workspaceRole) {
тут все будет сложнее, тебе надо сделать двустороннюю связь со стороны Workspace и со стороны Account тоже. Советую тебе прочитать [эту](https://vladmihalcea.com/the-best-way-to-map-a-many-to-many-association-with-extra-columns-when-using-jpa-and-hibernate/) статью как это делается.

2022-12-15 11:47 UTC, nekedio commented
Принял. Спасибо!

2023-01-09 10:28 UTC, dzencot commented
Тут еще ведется работа?

2023-01-09 12:07 UTC, nekedio commented
Да. Сегодня-завтра поправлю. Небольшая запара была.

2023-02-06 11:34 UTC, kacetal requested changes

2023-02-06 11:34 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/account/Account.java
> +            fetch = FetchType.EAGER,
LAZY

2023-02-06 11:34 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/domain/workspace/Workspace.java
> +            fetch = FetchType.EAGER,
LAZY

2023-02-06 11:34 UTC, kacetal commented on src/main/resources/templates/workspace/wks-users.html
> +                        <input type="hidden" name="wksName" th:value=${wksName}></input>
you can get wksName from url not from form

2023-02-06 11:34 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
> +        Long workspaceId = workspaceOptional.get().getId();
Pur all business logic check into the service layer

2023-02-06 23:47 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
> +        Long workspaceId = workspaceOptional.get().getId();
@nekedio Я это поправил, посмотри что именно я от тебя хотел. Остались мелочи с ленивыми полями.

2023-02-13 08:18 UTC, merged