fix #125 added mapstruct
Hexlet/hexlet-correction pull request #126
Opened 2023-02-10 07:10 UTC by anasasiia

- Добавила зависимости mapstruct
- Создала мапперы для Account, Typo и Workspace
- Создала аннотацию для маппинга LocalDateTime в String
- Переписала конвертеры с ручного маппинга на автоматический

2023-02-10 08:52 UTC, kacetal requested changes

2023-02-10 08:52 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/mapper/TypoMapper.java
> +@Mapper(componentModel = "spring", uses = {AccountMapper.class, TypoMapper.class})
не надо это `componentModel = "spring"` указывать каждый раз, достаточно один раз добавить [property](https://mapstruct.org/documentation/stable/reference/html/#configuration-options) в pom.xml

2023-02-10 08:52 UTC, kacetal commented on pom.xml
> +        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
используй последнюю версию

2023-02-10 08:52 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/converter/AccountToInfoAccount.java
> +    private final AccountMapper accountMapper = new AccountMapperImpl();
Ты у mapstruct используешь контекст spring, а значит что он будет добавлять к сгенерированным классам аннотацию @Component,  и Spring сам сможет создать, и заинжектить имплементацию.
В ручную ее создавать не нужно.

2023-02-10 08:52 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/mapper/WorkspaceMapper.java
> +    @GetDateAsString(getDateAsString = "")
Вообще мне кажется создание аннотаций тут будет лишним хватит и [метода](https://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods)

2023-02-10 12:41 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/converter/AccountToInfoAccount.java
> +        return accountMapper.toInfoAccount(source);
@kacetal а можно поподробнее узнать про первый вариант? Это к мапперам нужно добавить extends Converter<...>? А инжектить в AccountService, TypoService, WorkspaceService?

2023-02-10 13:37 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/converter/AccountToInfoAccount.java
> +        return accountMapper.toInfoAccount(source);
При первом варианте ты полностью удаляешь класс AccountToInfoAccount.java и инжектеш маппер на его место, и  используешь его напрямую.

2023-02-12 13:23 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/mapper/TypoMapper.java
> +@Mapper(componentModel = "spring", uses = {AccountMapper.class, TypoMapper.class})
исправила

2023-02-12 13:23 UTC, anasasiia commented on pom.xml
> +        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
исправила

2023-02-12 13:23 UTC, anasasiia commented on pom.xml
> +            <version>1.4.2.Final</version>
исправила

2023-02-12 13:23 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/converter/AccountToInfoAccount.java
> +    private final AccountMapper accountMapper = new AccountMapperImpl();
исправила

2023-02-12 13:23 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/mapper/WorkspaceMapper.java
> +    @GetDateAsString(getDateAsString = "")
исправила

2023-02-12 13:24 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/converter/AccountToInfoAccount.java
> +        return accountMapper.toInfoAccount(source);
удалила конвертеры, мапперы использовала напрямую в services. Надеюсь, правильно поняла

2023-02-13 08:33 UTC, kacetal requested changes
master обновился, подними ветку до последнего коммита и проверь не добавилось ли дополнительных мапперов в новом коммите.
```
Conflicting files
src/test/java/io/hexlet/typoreporter/service/converter/CreateWorkspaceToWorkspaceTest.java
```

2023-02-13 08:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +            .map(oldAcc -> accountMapper.toAccount(updateProfile))
Мне кажется тут нужно использовать метод который принимает два аргумента, профиль и старый аккаунт для обновления. Как это было до изменения.

2023-02-13 08:33 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/mapper/WorkspaceMapper.java
> +    default String getDateAsString(LocalDateTime date) {
Может лучше `getDateAgoAsString`

2023-02-13 08:33 UTC, kacetal commented on src/test/java/io/hexlet/typoreporter/service/mapper/TypoReportToTypoMapperTest.java
> +@SpringBootTest(classes = {TypoMapperImpl.class})
Не очень хорошо использовать прямую ссылку на имплементацию, до компиляции ее не существует, или к примеру у тебя изменится имя класса импленетации и из за этого упадут тесты. Да и не нужен нам контекст Spring для одного класса, лучше использовать стандартный механизм mapstruct для этого.

`private final WorkspaceMapper workspaceMapper = Mappers.getMapper(WorkspaceMapper.class);`

2023-02-13 15:01 UTC, anasasiia commented on src/test/java/io/hexlet/typoreporter/service/mapper/TypoReportToTypoMapperTest.java
> +@SpringBootTest(classes = {TypoMapperImpl.class})
Исправила

2023-02-13 15:01 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/mapper/WorkspaceMapper.java
> +    default String getDateAsString(LocalDateTime date) {
Исправила

2023-02-13 15:02 UTC, anasasiia commented on src/main/java/io/hexlet/typoreporter/service/AccountService.java
> +            .map(oldAcc -> accountMapper.toAccount(updateProfile))
Исправила

2023-02-14 14:26 UTC, kacetal requested changes
Осталось последнее, проверь почему у тебя так много лишних не используемых методов в мапперах и удали ненужные.

2023-02-14 14:26 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/mapper/TypoMapper.java
> +public interface TypoMapper {
В этом классе ты забыла маппинга даты. Я исправил.

2023-02-14 15:27 UTC, anasasiia commented
Ненужные методы удалила

2023-02-15 08:13 UTC, kacetal commented
@anasasiia Спасибо, теперь можно мержить.

2023-02-15 08:13 UTC, merged