[Hexlet#276]. Fix cors error. Update js script, update tests, add override handleMethodArgumentNotValid method
Hexlet/hexlet-correction pull request #279
Opened 2024-06-23 18:34 UTC by kitdim

Не прошёл один интеграционный тест. Тест недавно добавили. В предыдущем мердже он тоже не [прошёл](https://github.com/Hexlet/hexlet-correction/actions/runs/9551067216/job/26324546277).
[Демо](https://hexlet-correction-u17z.onrender.com)

2024-06-23 19:23 UTC, kitdim commented
Перед мерджем нужно будет поменять url для загрузки js скрипта, ща урл с рендера стоит 'https://hexlet-correction-u17z.onrender.com/api/workspaces'

2024-06-23 20:12 UTC, kitdim commented
![image](https://github.com/Hexlet/hexlet-correction/assets/45449261/e3c942e5-9889-4c38-a4c4-dea9ea7ab414)
js скрипт вытаскиваем так ` <script src="https://cdn.jsdelivr.net/gh/kitdim/hexlet-correction@fix-CORS-error/src/widget/index.js"></script>`

2024-06-26 06:38 UTC, Malcom1986 commented
Привет! Тест посмотрю, почему падает

2024-06-26 16:55 UTC, bazilval commented
@Malcom1986 там тест падает из-за баги в одном из предыдущих пулл реквестов
Вот тут (https://github.com/Hexlet/hexlet-correction/pull/278) эту багу исправят, плюс попутно некоторые вещи. Надо ревьюить, я тоже там погляжу

2024-06-26 17:03 UTC, bazilval commented
@kitdim привет!
Может тогда, раз мы взялись за валидацию в виджете, будем выводить ошибки валидации не с помощью alert, под соответствующими полями будем выводить сообщения об ошибке?

По сути к нам возвращается JSON с указанием где ошибка и в чём она заключается, надо пройти циклом и в зависимости от ключа, вписать в нужный div для ошибки сам текст предупреждения.

2024-06-26 17:29 UTC, bazilval commented
@kitdim используй тогда для этих div-ов класс бутстрапа "invalid-feedback", чтобы было однообразно с нашим основным сервисом и аккуратно смотрелось

2024-06-27 11:21 UTC, fey commented on src/widget/index.js
> +      workSpaceUrl: 'https://hexlet-correction-u17z.onrender.com/api/workspaces',
Тут вы ссылку поменяли, давайте вернем назад :)

2024-06-27 11:22 UTC, fey commented
Да, насчет алерта согласен. Лучше на форме это выводить.

2024-06-27 13:39 UTC, bazilval commented on src/widget/index.js
> +      workSpaceUrl: 'https://hexlet-correction-u17z.onrender.com/api/workspaces',
Я так понял это для нас, чтобы демо работало :)

2024-06-27 13:43 UTC, bazilval commented on src/main/java/io/hexlet/typoreporter/handler/domain/ApiError.java
> +        super();
А у кого мы в этом случае вызываем super(), если класс ни от кого не наследуется? У Object? Если так, то нет нужды в явном вызове super()

2024-06-27 13:45 UTC, bazilval commented on src/widget/index.js
> +  return response.status === 201;
Возможно проверку в один оператор, которая используется один раз, можно оставить в изначальном виде и не выносить в отдельную функцию

2024-06-29 19:04 UTC, kitdim commented
> @kitdim используй тогда для этих div-ов класс бутстрапа "invalid-feedback", чтобы было однообразно с нашим основным сервисом и аккуратно смотрелось

@fey, на самом деле усложняет всё. потому-что бутстрап может быть не на каждом сайте. то что у нас в примере, идеальный случай. мб, лучше так отрисовывать?

2024-06-29 19:28 UTC, kitdim commented
Я всё подготовил, но давайте на будующее этот момент тоже поправим
https://github.com/Hexlet/hexlet-correction/pull/279#issuecomment-2198310015

2024-06-30 16:47 UTC, bazilval commented
> > @kitdim используй тогда для этих div-ов класс бутстрапа "invalid-feedback", чтобы было однообразно с нашим основным сервисом и аккуратно смотрелось
> 
> @fey, на самом деле усложняет всё. потому-что бутстрап может быть не на каждом сайте. то что у нас в примере, идеальный случай. мб, лучше так отрисовывать?

@kitdim насчёт того, что у нас бутстрап может быть не на каждом сайте это верная мысль!
Может тогда добавим в описание стилей в начале, описание класса для ошибки? Либо по айдишнику (но тогда дублироваться будет описание для двух айдишиников)
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/1a8642f6-938d-46c4-95f0-0ca0e6aa8831)
Можно просто списать с бутстраповского значения

2024-07-02 20:41 UTC, kitdim commented
Сделал, можем сливать

2024-07-03 00:03 UTC, bazilval requested changes

2024-07-03 00:03 UTC, bazilval commented on src/widget/index.js
> +  const style = document.createElement('style');
И всё-таки я бы прям добавил этот стиль в уже существующее в [самом начале файла описание](https://github.com/Hexlet/hexlet-correction/blob/61f3be57917e58983146ca5d088a1f798c779a89/src/widget/index.js#L3) стилей

Чтобы просто всё оформление было в одном месте, для удобства поддержания

2024-07-03 06:45 UTC, kitdim commented on src/widget/index.js
> +  const style = document.createElement('style');
Я сделал так, потому что мы не можем гарантировать что конечный пользователь ввёдет что-то неправильно (длинный эмаёл или описание). А так если хочешь, то можешь сам подправить.

2025-06-02 15:30 UTC, closed without merging