Migration on gradle
Hexlet/hexlet-correction pull request #83
Opened 2022-02-21 08:04 UTC by zxvfc

2022-02-21 10:36 UTC, kacetal requested changes

2022-02-21 10:36 UTC, kacetal commented on build.gradle
> +    implementation(
как мне кажется лучше использовать не блоки а inline для области водомости зависимости, это менее вербозно

2022-02-21 10:36 UTC, kacetal commented on build.gradle
> +        'org.testcontainers:junit-jupiter:1.16.3',
для тест контейнеров лучше нужно использовать BOM для управления версиями

```
ext {
  set('testcontainersVersion', "1.16.2")
}
dependencies {
  ...
  testImplementation 'org.testcontainers:junit-jupiter'
  testImplementation 'org.testcontainers:postgresql'
}
dependencyManagement {
  imports {
    mavenBom "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
  }
}
```

2022-02-21 10:36 UTC, kacetal commented on build.gradle
> +java.sourceCompatibility = JavaVersion.VERSION_17
sourceCompatibility можно записать проще `sourceCompatibility = '17'`

2022-02-21 10:36 UTC, kacetal commented on build.gradle
> +
мне кажется не хватает конфигурации для lombok
```
configurations {
  compileOnly {
    extendsFrom annotationProcessor
  }
}
```

2022-02-21 10:36 UTC, kacetal commented on build.gradle
> +
для тестов
```
tasks.named('test') {
  useJUnitPlatform()
}
```

2022-02-21 10:36 UTC, kacetal commented on build.gradle
> +dependencies {
Ну и желательно вынести все версии которые не управляются Spring куда нибуть во вне из блока dependencies. Например так:
```
ext {
    webjarsLocatorVersion  = '0.42'
}

dependencies {
    ...
    implementation  "org.webjars:webjars-locator:$webjarsLocatorVersion"
}
```

2022-02-21 11:20 UTC, zxvfc commented
Поправил.

2022-02-21 16:02 UTC, fey commented
@zxvfc тесты падают :(

2022-02-22 08:42 UTC, kacetal commented
Не проходят тесты.

2022-02-22 08:47 UTC, zxvfc commented
Тесты падали из-за того, что не было jar-ника с враппером. Судя по всему не добавил его в коммит. Сейчас должно работать.

2022-02-22 08:47 UTC, kacetal requested changes

2022-02-22 08:47 UTC, kacetal commented on build.gradle
> +test {
Желательно разделить юнит и интеграционные тесты на две разных задачи как это было в мавен с помощью плагинов failsafe и surefire. Юнит тесты оканчиваются на *Test , а интеграционные на *IT.  В последних версиях градле можно использовать этот плагин: https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html

2022-02-22 08:47 UTC, kacetal commented on .github/workflows/github-ci.yml
> +        run: ./gradlew clean test
И думаю тут можно улучшить и использовать make чтобы не зависить от build системы.

2022-02-22 08:48 UTC, zxvfc commented on build.gradle
> +test {
Окей, поправлю

2022-02-22 08:50 UTC, zxvfc commented on build.gradle
> +test {
Может быть стои вынести интеграционные тесты в отдельный модуль (подпроект), который будет зависить от основных исходником? Тогда будет проще менеджить интеграционные тесты.

2022-02-22 08:52 UTC, zxvfc commented
Всё ещё падают...

2022-02-22 08:57 UTC, kacetal commented on build.gradle
> +test {
Так можно, главное проследить чтобы этот модуль правильно захватывал спринг конфигурацию и не было слошком вербозно.

2022-02-22 09:04 UTC, zxvfc commented
Ага, всё дело было в `.gitignore`!

2022-02-22 09:08 UTC, zxvfc commented on build.gradle
> +test {
Хм, вероятно стоит сделать это отдельно, в отдельном ПР. Я думаю там будет довольно много изменений и что бы не мешать всё в одну кучу так будет понятнее и удобнее.

2022-02-22 09:18 UTC, kacetal commented on build.gradle
> +test {
ok

2022-02-22 10:06 UTC, kacetal commented on .github/workflows/github-ci.yml
> +        run: ./gradlew clean test
@zxvfc

2022-02-22 21:41 UTC, merged