add Account DTO + Controller + Service
Hexlet/hexlet-correction pull request #99
Opened 2022-05-22 13:36 UTC by saymon-says

@kacetal Давай начнем

2022-05-24 20:52 UTC, kacetal commented
@saymon-says Оставь стандартные сообщения, Hibernate Validator может создать правильное сообщение об ошибке с помощью reflection.

2022-05-24 21:14 UTC, kacetal requested changes

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +        final var account = accountRepository.findAccountByEmail(email)
you can use projection or map to user here here

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +public class AccountServiceImpl implements UserDetailsService, AccountService {
выдели ту часть которая отвечает за безопасность в отдельный пакет "security". Не смениавай все в одном сервисе.

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +@RequestMapping(path = "")
A handler method that is not mapped to any path explicitly is effectively mapped to an empty path.

2022-05-24 21:14 UTC, kacetal commented on src/main/resources/templates/registration.html
> +                                    src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
don't use external image

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +    @PostMapping("/register")
use "signup" path

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +        model.addAttribute("login_active", "active");
no need you can use security context with thyme leaf

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +        model.addAttribute("accountRegistration", new AccountRegistration());
раздели сущности регистрации и логина, для логина тебе нужно всего два поля

2022-05-24 21:14 UTC, kacetal commented on src/main/java/io/hexlet/typoreporter/web/Templates.java
> +    static final String LOGIN = "sign_in";
kebab case for filename

2022-05-24 21:14 UTC, kacetal commented on src/main/resources/templates/login.html
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
смотри как использовать локальные ресурсы с контролем версий через мавен

2022-05-27 09:15 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/dto/account/AccountLogin.java
> +@NoArgsConstructor
ok

2022-05-27 09:26 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/dto/account/AccountRegistration.java
> +    @Email(message = "Email should be valid")
Касается только email? Стандартные сообщения кривые, поэтому я сделал адекватные. 
![Снимок экрана от 2022-05-27 12-23-09](https://user-images.githubusercontent.com/43708964/170671544-bd6e85a5-aa5d-4f37-b9a2-ab5113ea0aee.png) Я убрал свои сообщения и оставил только @NotBlank. Сделать красиво вывод ошибок под каждым полем я не смог. Тогда да, можно было бы оставить как есть.

2022-05-27 09:26 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +    private AccountRepository accountRepository;
ок

2022-05-27 09:29 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
ок

2022-05-27 09:32 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +public class AccountServiceImpl implements UserDetailsService, AccountService {
Это да. Сделал в одном потому что не понятно куда дальше должно идти. Ок, переделал на 2 сервиса

2022-05-27 09:32 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +@RequestMapping(path = "")
ок

2022-05-27 09:34 UTC, saymon-says commented on src/main/resources/templates/registration.html
> +                                    src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
это вообще было первый шаблон. Он не актуален уже.

2022-05-27 09:40 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +    @PostMapping("/register")
ok

2022-05-27 09:41 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/web/AccountController.java
> +        model.addAttribute("accountRegistration", new AccountRegistration());
Да, саму dto то сделал.

2022-05-27 09:45 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/web/Templates.java
> +    static final String LOGIN = "sign_in";
ok

2022-05-27 14:10 UTC, saymon-says commented on src/main/resources/templates/login.html
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
я убрал вообще, все равно не отображается иконка github

2022-05-29 17:25 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +    private Account fillInAccount(AccountRegistration accountRegistration, Account account) {
Я не знаю что это. А зачем?

2022-05-29 18:50 UTC, saymon-says commented on src/main/java/io/hexlet/typoreporter/service/account/AccountServiceImpl.java
> +    private Account fillInAccount(AccountRegistration accountRegistration, Account account) {
Теперь знаю. Сделал.

2022-06-03 15:21 UTC, fey commented
@kacetal подскажи, много ли критичных замечаний осталось?
Нам бы сервис в MVP запустить :hype:

2022-06-04 16:28 UTC, kacetal commented
> @kacetal подскажи, много ли критичных замечаний осталось?
> Нам бы сервис в MVP запустить :hype:

@fey Надо проверить работает ли оно, постараюсь на этих выходных проверить.

2022-06-04 17:53 UTC, fey commented
@saymon-says задеплой на хероку демку и скинь на нее ссылку

2022-06-08 16:25 UTC, saymon-says commented
Так а что там закидывать, если не готово.

2022-06-09 07:25 UTC, fey commented
@saymon-says а оно работает? :D 
Может тогда двигаться дальше и довести до рабочего состояния, чтобы можно было уже что-то делать?

2022-06-09 08:22 UTC, saymon-says commented
Да, регистрация работает. В базу складывает пользователей. У нас затык именно с авторизацией. Артём пока не проверил ПР, и я не могу разобраться что там не так в коде. У меня не работает

2022-06-09 09:40 UTC, fey commented
Давайте выкатывать то, что есть, там в ишшусе хотят делать приглашения в воркспейсы. А они не будут работать, если юзеров нет :)

2022-06-09 18:43 UTC, fey commented
@saymon-says тебе нужно конфликт порешать. Попробуй самостоятельно, желательно через ребейз (чтобы не было мердж-коммита). Если не получится, могу попробовать помочь позднее.

2022-06-15 18:16 UTC, closed without merging

2022-06-15 18:17 UTC, kacetal commented
@fey я закрою этот пр, слишком большая задача, будем решать по шагам.

@saymon-says создавай регистрацию, потом я помогу с логином.